import { Toaster } from '@/components/ui/sonner';
import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ConfettiProvider from '@/components/providers/ConfettiProvider';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang='en' className={inter.className}>
        <body>
          <ConfettiProvider />
          <Toaster
            className={inter.className}
            richColors
            closeButton
            duration={1500}
            position='top-center'
          />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
